name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem
      
      - name: Deploy to AWS server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy-key.pem ubuntu@16.171.226.162 '
            cd ~/mycompose &&
            git pull &&
            ansible-playbook deploy.yml --connection=local
          '
